mod aggregate;

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use rayon::prelude::*;
use tracing::debug;
use walkdir::WalkDir;

use aggregate::check_failure_surface_aggregate;

use crate::{
    config::{source_file_kind, GuardConfig, SourceKind},
    model::{Issue, ScanStats},
    path_match::{path_string, relative_path},
    plugins::{FailureSurfaceSignal, PluginHost, Scope},
};

const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "generated by",
    "do not edit",
    "code generated",
    "autogenerated",
    "auto-generated",
    "this file was generated",
];
const MIN_PARALLEL_SOURCE_FILES: usize = 8;

#[derive(Debug, Clone, Eq, PartialEq)]
pub(crate) struct ScanResult {
    pub(crate) issues: Vec<Issue>,
    pub(crate) stats: ScanStats,
}

pub(crate) fn run_scan(config: &GuardConfig) -> Result<ScanResult, String> {
    let root = canonical_root(&config.root)?;
    debug!(root = %root.display(), "starting scan");
    let host = PluginHost::bundled();
    debug_assert!(!host.manifests().is_empty());
    let mut plan = build_scan_plan(config, &host, &root)?;

    prewarm_source_kinds(&plan.source_kinds);
    let source_results = analyze_source_files(config, host, &plan.source_files)?;
    reduce_source_results(source_results, &mut plan);

    for (dir, children) in &plan.direct_children {
        let count = plan.child_counts.get(dir).copied().unwrap_or_default();
        host.run_scope(
            config,
            Scope::directory_children(dir, children, count),
            &mut plan.issues,
        );
    }
    check_failure_surface_aggregate(
        config,
        plan.stats.scanned_files,
        &plan.scanned_source_dirs,
        &plan.failure_surfaces,
        &mut plan.issues,
    );

    plan.issues.sort_by(|left, right| {
        (left.path.as_str(), left.line.unwrap_or(0), left.rule).cmp(&(
            right.path.as_str(),
            right.line.unwrap_or(0),
            right.rule,
        ))
    });
    debug!(
        matched_files = plan.stats.matched_files,
        scanned_files = plan.stats.scanned_files,
        generated_files = plan.stats.generated_files,
        unsupported_files = plan.stats.unsupported_files,
        excluded_entries = plan.stats.excluded_entries,
        source_jobs = plan.source_files.len(),
        issue_count = plan.issues.len(),
        "finished scan",
    );
    Ok(ScanResult {
        issues: plan.issues,
        stats: plan.stats,
    })
}

fn build_scan_plan(
    config: &GuardConfig,
    host: &PluginHost,
    root: &Path,
) -> Result<ScanPlan, String> {
    let mut plan = ScanPlan::default();
    let mut walk = WalkDir::new(root).into_iter();
    while let Some(entry) = walk.next() {
        let entry = entry.map_err(|error| format!("failed to walk source tree: {error}"))?;
        let path = entry.path();
        let relative = relative_path(root, path)?;

        if config.is_excluded(&relative) {
            plan.stats.excluded_entries += 1;
            debug!(path = %relative.display(), "excluded path");
            if entry.file_type().is_dir() {
                walk.skip_current_dir();
            }
            continue;
        }

        let scanned_entry = config.is_scanned(&relative);
        if scanned_entry {
            track_direct_child(&mut plan.direct_children, &relative);
        }

        if entry.file_type().is_dir() {
            if scanned_entry {
                plan.direct_children.entry(relative.clone()).or_default();
                host.run_scope(config, Scope::source_directory(&relative), &mut plan.issues);
                add_child_count(&mut plan.child_counts, &relative);
            }
            continue;
        }

        if !scanned_entry {
            continue;
        }
        plan.stats.matched_files += 1;
        host.run_scope(config, Scope::file_path(&relative), &mut plan.issues);

        let Some(kind) = source_file_kind(&relative) else {
            plan.stats.unsupported_files += 1;
            debug!(path = %relative.display(), "unsupported matched file");
            continue;
        };
        plan.source_kinds.insert(kind);
        plan.source_files.push(SourceFileJob {
            relative: relative.clone(),
            absolute: path.to_path_buf(),
            path: path_string(&relative),
            kind,
        });
    }
    Ok(plan)
}

#[derive(Debug, Default)]
struct ScanPlan {
    issues: Vec<Issue>,
    stats: ScanStats,
    child_counts: BTreeMap<PathBuf, usize>,
    direct_children: BTreeMap<PathBuf, BTreeSet<String>>,
    source_files: Vec<SourceFileJob>,
    source_kinds: BTreeSet<SourceKind>,
    scanned_source_dirs: BTreeMap<PathBuf, usize>,
    failure_surfaces: Vec<FailureSurfaceSignal>,
}

#[derive(Debug, Clone, Eq, PartialEq)]
struct SourceFileJob {
    relative: PathBuf,
    absolute: PathBuf,
    path: String,
    kind: SourceKind,
}

#[derive(Debug, Eq, PartialEq)]
struct SourceFileResult {
    relative: PathBuf,
    status: SourceFileStatus,
    issues: Vec<Issue>,
    failure_surfaces: Vec<FailureSurfaceSignal>,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
enum SourceFileStatus {
    Generated,
    Scanned,
}

fn prewarm_source_kinds(kinds: &BTreeSet<SourceKind>) {
    if kinds.contains(&SourceKind::Rust) {
        flavor_plugin_rust::plugin::prewarm();
    }
    if kinds.contains(&SourceKind::TypeScript) {
        flavor_plugin_typescript::plugin::prewarm();
    }
    if kinds.contains(&SourceKind::Vue) {
        flavor_plugin_vue::plugin::prewarm();
    }
    if kinds.contains(&SourceKind::Svelte) {
        flavor_plugin_svelte::plugin::prewarm();
    }
}

fn analyze_source_files(
    config: &GuardConfig,
    host: PluginHost,
    jobs: &[SourceFileJob],
) -> Result<Vec<SourceFileResult>, String> {
    if use_serial_source_analysis(jobs.len()) {
        return collect_source_results(
            jobs.iter()
                .enumerate()
                .map(|(index, job)| (index, analyze_source_file(config, host, job)))
                .collect(),
        );
    }

    let mut results = jobs
        .par_iter()
        .enumerate()
        .map(|(index, job)| (index, analyze_source_file(config, host, job)))
        .collect::<Vec<_>>();
    results.sort_by_key(|(index, _)| *index);
    collect_source_results(results)
}

fn collect_source_results(
    results: Vec<(usize, Result<SourceFileResult, String>)>,
) -> Result<Vec<SourceFileResult>, String> {
    let mut collected = Vec::with_capacity(results.len());
    for (_, result) in results {
        collected.push(result?);
    }
    Ok(collected)
}

fn use_serial_source_analysis(count: usize) -> bool {
    if count == 0 {
        return true;
    }
    let parallelism = std::thread::available_parallelism()
        .map(|value| value.get())
        .unwrap_or(1);
    count < MIN_PARALLEL_SOURCE_FILES || count < parallelism.saturating_mul(2)
}

fn analyze_source_file(
    config: &GuardConfig,
    host: PluginHost,
    job: &SourceFileJob,
) -> Result<SourceFileResult, String> {
    let source = fs::read_to_string(&job.absolute)
        .map_err(|error| format!("failed to read {}: {error}", job.absolute.display()))?;
    if is_generated_source(&source) {
        debug!(path = %job.relative.display(), "skipped generated source");
        return Ok(SourceFileResult {
            relative: job.relative.clone(),
            status: SourceFileStatus::Generated,
            issues: Vec::new(),
            failure_surfaces: Vec::new(),
        });
    }

    debug!(path = %job.relative.display(), kind = ?job.kind, "scanning source file");
    let mut issues = Vec::new();
    let mut failure_surfaces = Vec::new();
    host.run_scope_with_signals(
        config,
        Scope::source_file(&job.relative, &job.path, &source, job.kind),
        &mut issues,
        &mut failure_surfaces,
    );
    Ok(SourceFileResult {
        relative: job.relative.clone(),
        status: SourceFileStatus::Scanned,
        issues,
        failure_surfaces,
    })
}

fn reduce_source_results(results: Vec<SourceFileResult>, plan: &mut ScanPlan) {
    for result in results {
        match result.status {
            SourceFileStatus::Generated => {
                plan.stats.generated_files += 1;
            }
            SourceFileStatus::Scanned => {
                plan.stats.scanned_files += 1;
                add_child_count(&mut plan.child_counts, &result.relative);
                add_source_dir_counts(&mut plan.scanned_source_dirs, &result.relative);
                plan.issues.extend(result.issues);
                plan.failure_surfaces.extend(result.failure_surfaces);
            }
        }
    }
}

fn canonical_root(root: &Path) -> Result<PathBuf, String> {
    fs::canonicalize(root)
        .map_err(|error| format!("failed to resolve root {}: {error}", root.display()))
}

fn add_child_count(child_counts: &mut BTreeMap<PathBuf, usize>, relative: &Path) {
    let Some(parent) = relative.parent() else {
        return;
    };
    *child_counts.entry(parent.to_path_buf()).or_default() += 1;
}

fn add_source_dir_counts(counts: &mut BTreeMap<PathBuf, usize>, relative: &Path) {
    let mut current = normalize_dir(relative.parent().unwrap_or_else(|| Path::new(".")));
    loop {
        *counts.entry(current.clone()).or_default() += 1;
        if current.as_os_str() == "." {
            break;
        }
        current = normalize_dir(current.parent().unwrap_or_else(|| Path::new(".")));
    }
}

fn normalize_dir(path: &Path) -> PathBuf {
    if path.as_os_str().is_empty() {
        PathBuf::from(".")
    } else {
        path.to_path_buf()
    }
}

fn track_direct_child(child_map: &mut BTreeMap<PathBuf, BTreeSet<String>>, relative: &Path) {
    let Some(parent) = relative.parent() else {
        return;
    };
    let Some(name) = relative.file_name().and_then(|name| name.to_str()) else {
        return;
    };
    child_map
        .entry(parent.to_path_buf())
        .or_default()
        .insert(name.to_string());
}

fn is_generated_source(source: &str) -> bool {
    source.lines().take(12).any(|line| {
        let line = line.to_ascii_lowercase();
        GENERATED_MARKERS.iter().any(|marker| line.contains(marker))
    })
}
